# Generated by Django 4.1.4 on 2022-12-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_created_at_order_day_menu_order_ip_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, unique=True),
        ),
    ]
